name: CI - Build & Push Docker Images

on:
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKER_IMAGE_NAME }}-backend
  IMAGE_NAME_FRONTEND: ${{ secrets.DOCKER_IMAGE_NAME }}-frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image tag
        id: tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "VERSION=$SHORT_SHA" >> "$GITHUB_OUTPUT"
          echo "Image tag: $SHORT_SHA"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build & Push Backend Image
        run: |
          VERSION=${{ steps.tag.outputs.VERSION }}

          docker build \
            --build-arg NODE_ENV=production \
            --build-arg VERSION=$VERSION \
            --cache-from=type=registry,ref=$DOCKER_USERNAME/$IMAGE_NAME_BACKEND:latest \
            --cache-to=type=inline \
            -t $DOCKER_USERNAME/$IMAGE_NAME_BACKEND:$VERSION \
            -t $DOCKER_USERNAME/$IMAGE_NAME_BACKEND:latest \
            -f be/Dockerfile.prod \
            .

          docker push $DOCKER_USERNAME/$IMAGE_NAME_BACKEND:$VERSION
          docker push $DOCKER_USERNAME/$IMAGE_NAME_BACKEND:latest

      - name: Build & Push Frontend Image
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_API_SERVER_URL: ${{ secrets.NEXT_PUBLIC_API_SERVER_URL }}
        run: |
          VERSION=${{ steps.tag.outputs.VERSION }}

          docker build \
            --no-cache \
            --build-arg BUILD_TIME=$(date +%s) \
            --build-arg NODE_ENV=production \
            --build-arg VERSION=$VERSION \
            --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
            --build-arg NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
            --build-arg NEXT_PUBLIC_API_SERVER_URL=$NEXT_PUBLIC_API_SERVER_URL \
            -t $DOCKER_USERNAME/$IMAGE_NAME_FRONTEND:$VERSION \
            -t $DOCKER_USERNAME/$IMAGE_NAME_FRONTEND:latest \
            -f fe/Dockerfile.prod \
            .

          docker push $DOCKER_USERNAME/$IMAGE_NAME_FRONTEND:$VERSION
          docker push $DOCKER_USERNAME/$IMAGE_NAME_FRONTEND:latest

      - name: Build result
        if: success()
        run: |
          echo "Build & Push Success"
          echo "Tag: ${{ steps.tag.outputs.VERSION }}"
          echo "Backend: $DOCKER_USERNAME/$IMAGE_NAME_BACKEND"
          echo "Frontend: $DOCKER_USERNAME/$IMAGE_NAME_FRONTEND"
